version: '3.8'  # Specify the version of docker-compose

services:

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: video_summarizer
#    command: "--character-set-server=utf8mb4 --max-connections=100000 --sql-mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'"
    ports:
      - "3308:3306"
    networks:
      - vid-sum
#    logging:
#      driver: none
    volumes:
#      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -udevelopments -ppassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ffmpeg:
    container_name: vid-sum-ffmpeg
    image: jrottenberg/ffmpeg
    #tty: true
    networks:
      - vid-sum
    ports:
      - "29002:29000"
    tty: true
    entrypoint: "bash"

networks:
  vid-sum:
    driver: bridge



